# Generated by Django 4.2.27 on 2025-12-20 16:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=8, unique=True, verbose_name='Referencja')),
                ('ean', models.CharField(max_length=13, verbose_name='EAN')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('details_link', models.URLField(max_length=300, verbose_name='Dane Produkowe')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracker.productbase', to_field='reference')),
                ('product_brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='marka')),
                ('product_weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='waga')),
                ('product_measurement', models.CharField(blank=True, max_length=5, null=True, verbose_name='jednostka opisowa')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='wartość energetyczna')),
                ('fats', models.FloatField(blank=True, null=True, verbose_name='tłuszcz')),
                ('carbohydrates', models.FloatField(blank=True, null=True, verbose_name='węglowodany')),
                ('sugar', models.FloatField(blank=True, null=True, verbose_name='cukry')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='białko')),
                ('salt', models.FloatField(blank=True, null=True, verbose_name='sól')),
                ('category', models.CharField(blank=True, max_length=10, null=True, verbose_name='kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.productbase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
