# Generated by Django 5.2.9 on 2025-12-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='Upload date')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
