# Generated by Django 5.2.9 on 2025-12-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
