# Generated by Django 4.2.27 on 2025-12-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(max_length=1000),
        ),
    ]
