# Generated by Django 4.2.27 on 2026-01-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_receiptimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='product_measurement',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='product_weight',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='sugar',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_description',
            field=models.CharField(max_length=10000, null=True, verbose_name='marka'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_brand',
            field=models.CharField(max_length=200, null=True, verbose_name='marka'),
        ),
        migrations.AlterField(
            model_name='receiptimage',
            name='image',
            field=models.ImageField(upload_to='receipt_images/'),
        ),
    ]
