# Generated by Django 4.2.27 on 2026-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_productdetails_calories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbase',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterField(
            model_name='productbase',
            name='product_name',
            field=models.CharField(max_length=100000, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_brand',
            field=models.CharField(max_length=100000, null=True, verbose_name='marka'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_description',
            field=models.CharField(max_length=100000, null=True, verbose_name='marka'),
        ),
    ]
